-- Insert 10 mock data entries into the properties table
INSERT INTO properties
(property_name, property_type, description, address, price, rating,
 room_count, bed_count, max_number_of_guests, social_media_link, wifi, tv, separate_beds, private_bath,
 cooking_facilities, radio, towels,
 extra_bed_possible, bed_linen, fridge, coffee_machine, microwave, dishwasher, wc, terrace,
 kettle, bathtub, garden, cooking_utensils, washing_machine, self_check_in, smoking, quiet_location,
 good_transportation, shops_nearby, neighborhood, bathrooms, created_at,
 is_favorite, city_id)

VALUES ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3),

       ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3),
       ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3),
       ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3),
       ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3),
       ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3),
       ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3),
       ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3),
       ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3),
       ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3),
       ('Cosy Apartment', 'Wohnung', 'A quiet apartment in the city center.', 'Mitte X Strasse', 15, 4.5, 2, 2, 5,
        'https://www.monteurzimmer.de/wohnung/13597-berlin-d409273a52',
        TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE,
        TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE,
        'Mitte', 1, NOW(), true, 3);